API/API/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'API.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/',    include('polls.urls', namespace="polls")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
]

API/accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    # Session Login
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^auth/$',  views.login_form, name='login_form'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

API/polls/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views



urlpatterns = [
    # Regular Django Views
    url(r'^$', views.index, name='index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # # API views
    url(r'^api/questions/$', views.QuestionList.as_view()),
    url(r'^api/questions/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view()),
    # url(r'^api/choices/(?P<pk>[0-9]+)/$', api_views.ChoiceDetail.as_view()),
    # url(r'^api/create_user/$', api_views.UserCreate.as_view()),
    # url(r'^api/users/(?P<pk>[0-9]+)/$', api_views.UserDetail.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

API/accounts/models.py
from django.db import models

# Create your models here.

API/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

API/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.conf import settings

# Create your views here.



def login_form(request):
    return render(request, 'login.html', {})




def login_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        # the password verified for the user
        if user.is_active:
            login(request, user)
            return redirect('/polls/')
    return redirect(settings.LOGIN_URL, request)





def logout_user(request):
    logout(request)
    return redirect('/polls/')

API/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from rest_framework import generics


from django.contrib.auth.models import User
from .serializers import QuestionSerializer, ChoiceSerializer, UserSerializer


from .models import Choice, Question

@login_required
def index(request):
    template_name = 'base.html'
    return render(request, template_name, {})



class QuestionList(generics.ListCreateAPIView):
    """
    Get / Create questions
    """
    queryset = Question.objects.all()
    
    serializer_class = QuestionSerializer


class QuestionDetail(generics.RetrieveDestroyAPIView):

    """
    Get / Delete questions
    """
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer




def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choices.get(pk=request.POST['choice'])
        print selected_choice
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))




class ResultsView(generic.DetailView):
    model = Question
    template_name = 'results.html'

API/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Angular + Django</title>
        <script src="{% static 'angular/angular.min.js' %}"></script>
        <script src="{% static 'angular/angular-route.min.js' %}"></script>
        <script src="{% static 'app.js' %}"></script>
    </head>
    <body ng-app="pollsApp">

      {% verbatim %}
        <div ng-controller="PollsController">
          <div ng-view>
          </div>
        </div>
      {% endverbatim %}

    </body>
</html>

API/templates/detail.html
<h1>{{ question.question_text }}</h1>

<div ng-repeat="choice in question.choices">
    <label>
      <input type="radio" data-ng-model="selected_choice.choice" ng-value="{{choice.id}}"  />
      {{ choice.choice_text }}
    </label><br />
</div>
<input type="button" ng-click="addVote()" value="Vote" />
</form>

API/templates/index.html
<p>index</p>

API/templates/login.html
<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    Username: <input type='text' name='username' />
    <br>
    Password: <input type='password' name='password' />
    <br>
    <input type='submit' value='Login' />
  </form>
  

API/templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
<div ng-repeat="choice in question.choices">
    <li>{{ choice.votes }}</li>
</div>
</ul>

<a ng-href="/polls/#/polls/{{question.id}}">Vote again?</a>